### ISSUE TITLE
Youtube music album id changed

### ISSUE THREAD

**Issue by elbkr** [EvasiveXkiller/youtube-moosick#162]
**Describe the bug**
The id of youtube music albums no longer start with MPREb, so the function doesn't find any album/single/ep if you try to use getAlbum function

**To Reproduce**
1. Get a youtube music album link
2. Extract the album id from the url
3. Use `ytmoosick.getAlbum(id)

**Comment by EvasiveXkiller** [comment]
Hi @elbkr , could you please provide a minimal reproducible code with the album that you tried?

**Comment by elbkr** [comment]
> Hi @elbkr , could you please provide a minimal reproducible code with the album that you tried?

I tried using:
1. an album: https://music.youtube.com/playlist?list=OLAK5uy_k9SPz_NIfDcnoYLc8rz_RnKe7SAp7ySj0
2. a playlist: https://music.youtube.com/playlist?list=PL4fGSI1pDJn4jhQB4kb9M36dvVmJQPt4T
3. an ep: https://music.youtube.com/playlist?list=OLAK5uy_kmftZyDCsI9b19tk6tRXh0jCb3i_ER260

**Comment by elbkr** [comment]
And this is the code I used: 
```js
await ytmusic.search(linkID).then(res => {
console.log(res)
})

//also tried with .getAlbum and .getPlaylist

**Comment by EvasiveXkiller** [comment]
It seems like Youtube has default to the OLAK format, which this lib currently does not support. The old MPREb formats all still works, however they end up redirecting to the OLAK format. 

I dont have that much time to fully look into this at the moment. 
Feel free to open a pull request if you get OLAK parser to work.
